### ISSUE TITLE
dubbo的demo1调用demo2例子根本就没有回滚！

### ISSUE THREAD

**Issue by hvangzg** [1991wangliang/dubbo-lcn-demo#1]
dubbo的demo1调用demo2例子根本就没有回滚！照样插入到数据库中！！

**Comment by xlorne** [comment]
不会的，demo是都测试过的。你先确保本地事务没问题，LCN的本质是通过协调本地事务达到分布式事务一致性的效果的。😀😀

**Comment by chinesechina** [comment]
我的问题也和他一样了，当前事务是有回滚了，但是test2service 则是没有回滚的了

**Comment by xlorne** [comment]
Dubbo Demo使用讲解地址：[http://www.txlcn.org/video.html](http://www.txlcn.org/video.html)
